### ISSUE TITLE
Vision API Error isn't thrown

### ISSUE THREAD

**Issue by nnegrey** [googleapis/python-vision#3]
Was updating some samples and found when calling the Google Cloud Vision API with the python client library which has some handwritten helper methods making it a partial GAPIC library, that if the users passes a URL that the API can't reach, the API returns an error message, but the client library doesn't `throw` the error rather returns it as part of the response.

Call request: `response = client.text_detection(image=image)`
If you examine the response object from the api you'll find this:
```
error {
  code: 3
  message: "The URL does not appear to be accessible by us. Please double check or download the content and pass it in."
}
```
Seems like we should throw this error.

Related PR that I discovered this in: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2569

**Comment by busunkim96** [comment]
It doesn't look like the handwritten layer is changing the error. I get the same result when I call `batch_annotate_images` directly:



```py
from google.cloud import vision

client = vision.ImageAnnotatorClient()

source = vision.types.ImageSource(image_uri="https://bad-url")
image = vision.types.Image(source=source)
feature = vision.types.Feature(type="TEXT_DETECTION")

request = vision.types.AnnotateImageRequest(image=image, features=[feature])
response = client.batch_annotate_images(requests=[request])
```

```
responses {
  error {
    code: 14
    message: "We can not access the URL currently. Please download the content and pass it in."
  }
}
```

I believe this is because the API returns a `Response` object with an error field instead of a gRPC error. See [`wrap_method`](https://github.com/googleapis/python-api-core/blob/2010373b27536d1191175624b297a709d70153fa/google/api_core/gapic_v1/method.py#L148), [`wrap_errors`](https://github.com/googleapis/python-api-core/blob/eaf7aea4ba0e897b948a5763992f00825f6073ea/google/api_core/grpc_helpers.py#L151), and [`_wrap_unary_errors`](https://github.com/googleapis/python-api-core/blob/eaf7aea4ba0e897b948a5763992f00825f6073ea/google/api_core/grpc_helpers.py#L50-L59). 

The code that triggers a conversion from gRPC error to `google.api_core.exceptions` checks for a `grpc.RpcError`.

```py
        except grpc.RpcError as exc:
            six.raise_from(exceptions.from_grpc_error(exc), exc)
```

**Comment by munkhuushmgl** [comment]
@busunkim96 Let me know how I can help to resolve this issue.
