### ISSUE TITLE
Vision - Using Batch Offline Annotation asynchronously

### ISSUE THREAD

**Issue by Mayson12381** [googleapis/python-vision#5]
I am currently implementing a GCloud function applying the vision API to given images. Currently, the function is running for about 30 seconds (5 images) using the _async_batch_annotate_images_. My goal was to call the async method to leave the function early to save computing time.

This is the last part of my code,  everything works so far:

```
    # loop over the images and prepare them

    source = {'image_uri': input_image_uri}
    image = {'source': source}
    type_ = enums.Feature.Type.TEXT_DETECTION
    features_element = {'type': type_}
    features = [features_element]
    requests_element = {'image': image, 'features': features}
    requests.append(requests_element)

gcs_destination = {'uri': output_uri}
output_config = {'gcs_destination': gcs_destination, 'batch_size': 1}

client.async_batch_annotate_images(requests, output_config)

return True
```

How is it possible to call the async method and terminate the function right after the call to save computing time?
(@tseaver  maybe you could help?)

**Comment by brendanlundy** [comment]
Vision async methods must use GCS URIs rather than sending the content inline.

It is specifically mentioned for async files: https://cloud.google.com/vision/docs/reference/rest/v1/InputConfig

It isn't mentioned in the docs for async images, but the error message above is correct: https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest#image
