### ISSUE TITLE
cannot import types from google cloud vision  after creating virtual env

### ISSUE THREAD

**Issue by devineeharika** [googleapis/python-vision#59]
ImportError: cannot import name 'types'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by busunkim96** [comment]
Hi @devineeharika,

It looks like you are using the 2.0.0 version of the library with 1.0.0 code. If your code was previously working, you can pin to the previous version `google-cloud-vision==1.0.0`. Otherwise please reference the [samples](https://github.com/googleapis/python-vision/tree/master/samples) and [Migration Guide](https://github.com/googleapis/python-vision/blob/master/UPGRADING.md) to make your code compatible with the latest release (2.0.0)
