### ISSUE TITLE
Pickling a AnnotateImageResponse is no longer possible?

### ISSUE THREAD

**Issue by tkaymak** [googleapis/python-vision#74]
#### Environment details

  - OS type and version: MacOS 10.15.7
  - Python version: 3.7.5
  - pip version: `pip --version`
  - `google-cloud-vision` version: 2.0.0

#### Code example

```python
client = vision.ImageAnnotatorClient()
 The name of the image file to annotate
file_name = os.path.abspath('some_file')

# use the stable model as the new one that will be rolled out soon,
# might break things
features = [
    vision.Feature(type_=vision.Feature.Type.LABEL_DETECTION, model="builtin/stable"),
]

with open(file_name, 'rb') as image_file:
        content = image_file.read()

image = vision.Image(content=content)

response = client.annotate_image(request={
    'image': image,
    'features': features}, retry=retry.Retry(deadline=3))

# trying to pickle or dill will fail:
import pickle
with io.open("thing.pickle", 'wb') as f:
    pickle.dump(response,f )

```

#### Stack trace
```
*** _pickle.PicklingError: Can't pickle <class 'AnnotateImageResponse'>: attribute lookup AnnotateImageResponse on __main__ failed
```

We are using pickle to pickle a response from Cloud Vision API and put it into a local cache to process images faster.
The new 2.0.0 seems to break this functionality. I found [this](https://stackoverflow.com/a/64416662/5497956) workaround on SF, but it means we will loose all our previous cache information.

**Comment by busunkim96** [comment]
Hi @tkaymak,

proto-plus offers a few options for serialization (bytes, JSON, and dictionaries). https://proto-plus-python.readthedocs.io/en/stable/messages.html#serialization

These call the protobuf serialization functions under the hood. https://developers.google.com/protocol-buffers/docs/pythontutorial#why-use-protocol-buffers Using one of these methods is preferable to Python pickling because changes in the schema will be better handled. You can also share the bytes or JSON with implementations of protobuf in other languages.

It seems unlikely we'll support pickling proto-plus messages, but you can follow along on this thread for any updates. https://github.com/googleapis/proto-plus-python/issues/162

**Comment by tkaymak** [comment]
@busunkim96 thank you!
